 
  SpaceShip:
    trainer: ppo
    batch_size: 512
    beta: 5e-3
    buffer_size: 8192
    epsilon: 0.3
    hidden_units: 128
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 3e7
    memory_size: 64
    normalize: false
    num_epoch: 6
    num_layers: 4
    time_horizon: 64
    sequence_length: 64
    summary_freq: 20000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99